# Generated by Django 3.2.6 on 2021-09-22 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppnent_hand', models.CharField(choices=[('rock', 'グー'), ('paper', 'チョキ'), ('scissors', 'パー')], max_length=8, verbose_name='相手の手')),
                ('my_hand', models.CharField(choices=[('rock', 'グー'), ('paper', 'チョキ'), ('scissors', 'パー')], max_length=8, verbose_name='自分の手')),
                ('result', models.CharField(choices=[('win', '勝ち'), ('lose', '負け'), ('draw', 'あいこ')], max_length=4, verbose_name='対戦結果')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='janken.opponent', verbose_name='対戦相手')),
            ],
        ),
    ]
