# Generated by Django 3.2.6 on 2021-09-22 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('janken', '0002_match'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Game',
        ),
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
    ]
