# Generated by Django 3.2.6 on 2021-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0003_auto_20210922_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='oppnent_hand',
            new_name='opponent_hand',
        ),
    ]
