# Generated by Django 3.2.6 on 2021-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janken', '0004_rename_oppnent_hand_game_opponent_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_hand',
            field=models.CharField(choices=[('0', 'グー'), ('1', 'チョキ'), ('2', 'パー')], max_length=1, verbose_name='自分の手'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent_hand',
            field=models.CharField(choices=[('0', 'グー'), ('1', 'チョキ'), ('2', 'パー')], max_length=1, verbose_name='相手の手'),
        ),
    ]
